### ISSUE TITLE
Errors when running KP01 experiments: request for Dockerfile or requirements file

### ISSUE THREAD

**Issue by matsilv** [Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize#3]
Hello, and thank you for making this project available!

I attempted to run the KP01 example in this repository but encountered a few errors under different Python and package versions. 
I run the code with the command `python train.py` inside the `code/0-1 knapsack folder`.
Below, I detail the environments I tested and the issues I faced.

## Version 1

OS: Microsoft Windows 11 Home

Python version: 3.11.5

Packages: 
	numpy==2.2.0
	gurobipy==12.0.0
	torch==2.5.1
	scikit-learn==1.6.0
	pandas==2.2.3
	joblib==1.4.2
	scipy==1.14.1

Error:

```
Traceback (most recent call last):
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 523, in <module>
    clf.fit(feature_train, value_train)
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 362, in fit
    x_s2 = IPOfunc(A=A_torch, b=b_torch, h=h_torch, cTrue=-c_torch, GTrue=G_torch, purchase_fee=self.purchase_fee, compensation_fee=self.compensation_fee, max_iter=self.max_iter, thr=self.thr, damping=self.damping,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv\Lib\site-packages\torch\autograd\function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 1344, in forward
    c_, G_, h_,A_, b_,bounds_, x0,n_x,n_eq,n_ub = _preprocess(c_, A_, b_, G_, 
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 1231, in _preprocess
    c, A_ub, b_ub, A_eq, b_eq, bounds, x0 = _clean_inputs(c=c, A_ub=G, b_ub =h,A_eq=A,b_eq=b,
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 141, in _clean_inputs
    c = np.array(c, dtype=np.float, copy=True).squeeze()
                          ^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv\Lib\site-packages\numpy\__init__.py", line 410, in __getattr__
    raise AttributeError(__former_attrs__[attr], name=None)
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
    

As suggested in the error message, I replaced np.float with float. However this led to another error:

```
Traceback (most recent call last):
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 523, in <module>
    clf.fit(feature_train, value_train)
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 362, in fit
    x_s2 = IPOfunc(A=A_torch, b=b_torch, h=h_torch, cTrue=-c_torch, GTrue=G_torch, purchase_fee=self.purchase_fee, compensation_fee=self.compensation_fee, max_iter=self.max_iter, thr=self.thr, damping=self.damping,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv\Lib\site-packages\torch\autograd\function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 1416, in forward
    d_x,d_y,d_t, d_tau, d_kappa,solved = _get_delta(A_,b_,c_,x,y,t,tau,kappa,gamma,eta,pc= pc)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 854, in _get_delta
    alpha = _get_step(x, d_x, t, d_t, tau, d_tau, kappa, d_kappa, 1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\ip_model_whole.py", line 888, in _get_step
    alpha = np.min([1, alpha_x, alpha_tau, alpha_t, alpha_kappa])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv\Lib\site-packages\numpy\_core\fromnumeric.py", line 3302, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv\Lib\site-packages\numpy\_core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
```

## Version 2

OS: Microsoft Windows 11 Home

Python version: 3.8.10

Packages: 
	numpy==1.19.0
	gurobipy==11.0.3
	torch==2.4.1 (I also tested versions 2.0.0, 1.13.1)
	scikit-learn==1.3.2
	joblib==1.4.2
	scipy==1.9.0

Error:

```
Traceback (most recent call last):
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 523, in <module>
    clf.fit(feature_train, value_train)
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 399, in fit
    newLoss.backward()
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv38\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv38\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 2]], which is output 0 of ReluBackward0, is at version 10; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

I ensured this was not due to Windows-specific issues by running the code inside a Docker container, but the same error occurred.
Here is the Dockerfile I used:

```
FROM python:3.8

WORKDIR /app

COPY requirements.txt /app/requirements.txt

COPY code /app/code

RUN pip install --no-cache-dir -r requirements.txt
```

Could you kindly provide:

1. A requirements.txt file listing the package versions used.
2. Optionally, a Dockerfile to replicate your environment precisely.

Thank you in advance for your assistance. Please let me know if more information is required.

**Comment by Elizabethxyhu** [comment]
Hello,

Thank you for posting this issue. The first warning you encountered is due to differing versions of NumPy. Could you please use numpy==1.23.5? With that version, the original code we provided should run without issues.

If you have any further questions, please feel free to contact me.

Best,
Eliza

**Comment by matsilv** [comment]
Using numpy==1.23.5 does indeed resolve the first issue I mentioned, but I am still encountering the second error described in my previous post:

```
Traceback (most recent call last):
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 523, in <module>
    clf.fit(feature_train, value_train)
  File "NeurIPS_Two_Stage_Predict-Optimize\code\0-1 knapsack\train.py", line 399, in fit
    newLoss.backward()
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv38\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "NeurIPS_Two_Stage_Predict-Optimize\.venv38\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 2]], which is output 0 of ReluBackward0, is at version 10; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

After further investigation, I believe I might have identified the source of the issue.
It seems the problem originates from [line 342](https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/7ab17112cc99f2748f2b4817d991cf0b236c9d40/code/0-1%20knapsack/train.py#L342) of `train.py`.
By setting `torch.autograd.set_detect_anomaly(True)`, it seems that the problematic tensor is the one referenced by `op`.
Moreover, the tensor shape ([10,2]) mentioned in the error is compatible with shape of `op` and the version 10 is probably itemNum (i.e. the number of iterations).

Does this explanation make sense to you? Can I safely remove that instruction?

**Comment by Elizabethxyhu** [comment]
Yes. I agree that you can remove line 342 of train.py and have a try.

Please feel free to contact me if you need further help.

Best,
Eliza

**Comment by matsilv** [comment]
The fix appears to solve the issue.

However, I still have some questions: in [line 133](https://github.com/Elizabethxyhu/NeurIPS_Two_Stage_Predict-Optimize/blob/7ab17112cc99f2748f2b4817d991cf0b236c9d40/code/0-1%20knapsack/train.py#L333), isn’t there a possibility that the network is reinitialized during training?

**Comment by Elizabethxyhu** [comment]
Line 133 is designed to handle extreme cases, such as predictions that include zero, NaN, or infinity, which occur rarely.

If you have any further questions, please feel free to reach out. We can arrange a Zoom meeting if necessary.

Best,
Eliza

**Comment by matsilv** [comment]
Ok, thank you very much for the availability!
